feature: Added support for generating release notes + fixed a bug w.r.t. uploading to ecr public repo
aws/sagemaker-distribution pull request #21
Opened 2023-06-12 23:50 UTC by balajisankar15

feature: Added support for generating release notes + fixed a bug w.r.t. uploading to ecr public repo
*Issue #, if available:* N/A

*Description of changes: feature: Added support for generating release notes + fixed a bug w.r.t. uploading to ecr public repo

Release Notes can be generated using the following command

```
python ./src/main.py generate-release-notes --target-patch-version 0.1.0 --source-patch-version 0.0.2 
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-13 16:36 UTC, ketan-vijayvargiya requested changes
Overall, I don't see why `generate-release-notes` is a new command.

There was a specific reason we kept `create-xyz-version-artifacts` and `build` commands separate: it gives an opportunity for a human to change the list of marquee libraries, modify `Dockerfile` etc. in between. But I don't see the purpose of `generate-release-notes` being a separate command - isn't this something that should *always* and automatically be called whenever a `build` is triggered?

Moreover, having it separate introduces one more manual step and one more possible source of human error.

2023-06-13 17:21 UTC, balajisankar15 commented on build_artifacts/v0/v0.0/v0.0.1/RELEASE-cpu.md
> +* ipython is upgraded from 8.12.1 to 8.12.2
Addressed as part of the revision

2023-06-13 17:21 UTC, balajisankar15 commented on build_artifacts/v0/v0.0/v0.0.1/RELEASE-cpu.md
> +* ipython is upgraded from 8.12.1 to 8.12.2
(Introduced Markdown tables)

2023-06-13 17:25 UTC, balajisankar15 commented
"Build" script doesn't know what was the previous version from which this particular version was generated. This script needs that information to figure out which packages changed. @ketan-vijayvargiya .

It doesn't make sense for us to add source-patch-version parameter to the build script.

Re: This being an additional manual step
In the future when we automate the entire workflow, the automation should invoke these scripts separately.

2023-06-26 19:29 UTC, balajisankar15 commented
> Overall, I don't see why `generate-release-notes` is a new command.
> 
> There was a specific reason we kept `create-xyz-version-artifacts` and `build` commands separate: it gives an opportunity for a human to change the list of marquee libraries, modify `Dockerfile` etc. in between. But I don't see the purpose of `generate-release-notes` being a separate command - isn't this something that should _always_ and automatically be called whenever a `build` is triggered?
> 
> Moreover, having it separate introduces one more manual step and one more possible source of human error.

Done. During creation of a new version, I will be generating a new file which has the source patch version. 
During the build , I will use that file and generate change logs

2023-08-28 16:42 UTC, closed without merging