Add RTC extension and scripts
aws/sagemaker-distribution pull request #277
Opened 2024-03-19 20:47 UTC by zuoyuanh

Add RTC extension and scripts

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-03 17:01 UTC, claytonparnell requested changes

2024-04-03 17:01 UTC, claytonparnell commented on test/test_artifacts/v1/jupyter-collaboration.test.Dockerfile
> +ARG COSMOS_IMAGE
Can you update this to 
```
ARG SAGEMAKER_DISTRIBUTION_IMAGE
FROM $SAGEMAKER_DISTRIBUTION_IMAGE

2024-04-03 17:12 UTC, claytonparnell approved these changes

2024-04-04 17:27 UTC, nikhilumeshsargur approved these changes
Approving the change

2024-04-04 17:31 UTC, merged