Set up pre-commit hooks and workflows to check code style
aws/sagemaker-distribution pull request #313
Opened 2024-03-25 22:09 UTC by aws-tianquaw

*Issue #, if available:*
Currently the code base doesn't have any code stile check machnism.

*Description of changes:*
- Add pre-commit hooks to run code style formatters including black, isort, autoflake
- Run formatters on all existing files in this code base
- Add a git action workflow to check code styles whenever a new pull request is created and whenever something is pushed

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-25 23:09 UTC, claytonparnell requested changes
We should run all the unit tests (tests/test_main.py etc.) to make sure none of the functionality is impacted. And probably run a build/test/push as well.

2024-03-25 23:09 UTC, claytonparnell commented on DEVELOPMENT.md
> +pip install pre-commit
given we have instructed to conda install the environment.yml which includes pre-commit, we don't need to additionally pip install the package.

2024-03-26 17:08 UTC, balajisankar15 commented
Once this is merged, can you also rebase 2.0.0-beta with these changes?

2024-03-27 00:42 UTC, aws-tianquaw commented
> We should run all the unit tests (tests/test_main.py etc.) to make sure none of the functionality is impacted. And probably run a build/test/push as well.

Executed the local build/test and got the following results:
```
=========================== short test summary info ============================
FAILED tests/unit/sagemaker/serve/builder/test_transformers_builder.py::TestTransformersBuilder::test_build_deploy_for_trans
formers_local_container_and_remote_container
FAILED tests/unit/sagemaker/serve/model_server/triton/test_server.py::TritonServerTests::test_start_invoke_destroy_local_tri
ton_server_cpu
FAILED tests/unit/sagemaker/serve/model_server/triton/test_server.py::TritonServerTests::test_start_invoke_destroy_local_tri
ton_server_gpu
= 3 failed, 7668 passed, 3778 skipped, 2 deselected, 3 xpassed, 3308 warnings in 1619.18s (0:26:59)
```
The failed tests exactly match what is documented in https://github.com/aws/sagemaker-distribution/issues/316, so we can conclude that this PR doesn't introduce any new test failure.

2024-03-27 00:42 UTC, aws-tianquaw commented
> Once this is merged, can you also rebase 2.0.0-beta with these changes?

Sure I'll make sure to do it once this PR is merged

2024-03-27 17:22 UTC, claytonparnell approved these changes

2024-03-28 17:41 UTC, balajisankar15 approved these changes

2024-03-28 18:34 UTC, merged